// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Address struct {
	ID          int32
	CustomerID  int32
	Addr1       string
	Addr2       string
	Addr3       string
	Description string
}

type Category struct {
	ID          int32
	Name        string
	Description sql.NullString
	ImageUrl    sql.NullString
}

type Customer struct {
	ID       int32
	Name     string
	Mobile   string
	Email    string
	Password string
}

type Driver struct {
	ID              int32
	UserID          sql.NullInt32
	VehicleType     sql.NullString
	VehiclePlate    sql.NullString
	LicenseNumber   sql.NullString
	Available       sql.NullBool
	Rating          sql.NullString
	TotalDeliveries sql.NullInt32
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type DriverLocation struct {
	ID        int32
	DriverID  sql.NullInt32
	Latitude  float64
	Longitude float64
	UpdatedAt sql.NullTime
}

type MenuItem struct {
	ID          int32
	CategoryID  sql.NullInt32
	Name        string
	Description sql.NullString
	Price       string
	ImageUrl    sql.NullString
	Available   sql.NullBool
}

type MenuItemOption struct {
	ID         int32
	MenuItemID sql.NullInt32
	Name       string
	Price      sql.NullString
}

type Order struct {
	ID              int32
	UserID          sql.NullInt32
	DriverID        sql.NullInt32
	TotalAmount     string
	Status          sql.NullString
	PaymentMethod   sql.NullString
	DeliveryAddress sql.NullString
	Notes           sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type OrderItem struct {
	ID         int32
	OrderID    sql.NullInt32
	MenuItemID sql.NullInt32
	Quantity   int32
	Price      string
	Note       sql.NullString
}

type OrderItemOption struct {
	ID              int32
	OrderItemID     sql.NullInt32
	OptionID        sql.NullInt32
	PriceDifference sql.NullString
}

type Payment struct {
	ID              int32
	OrderID         sql.NullInt32
	Amount          sql.NullString
	Status          sql.NullString
	TransactionID   sql.NullString
	PaymentProvider sql.NullString
	CreatedAt       sql.NullTime
}

type Token struct {
	ID           int32
	UserID       sql.NullInt32
	RefreshToken string
	ExpiresAt    time.Time
	Revoked      sql.NullBool
	CreatedAt    sql.NullTime
}

type User struct {
	ID           int32
	Name         string
	Email        string
	PasswordHash string
	Phone        sql.NullString
	Role         sql.NullString
	Address      sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
