// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: foods_orders.sql

package database

import (
	"context"
)

const createFoodsOrder = `-- name: CreateFoodsOrder :exec
INSERT INTO foods_orders (order_id,customer_id,food_id,quantity)
VALUES ($1,$2,$3,$4)
RETURNING order_id, customer_id, food_id, quantity
`

type CreateFoodsOrderParams struct {
	OrderID    int32
	CustomerID int32
	FoodID     int32
	Quantity   int32
}

func (q *Queries) CreateFoodsOrder(ctx context.Context, arg CreateFoodsOrderParams) error {
	_, err := q.db.ExecContext(ctx, createFoodsOrder,
		arg.OrderID,
		arg.CustomerID,
		arg.FoodID,
		arg.Quantity,
	)
	return err
}
