// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Customer struct {
	ID     int32
	Name   string
	Mobile string
	Email  string
}

type Food struct {
	ID       int32
	Name     string
	Price    int32
	Picture  string
	Category string
}

type FoodsOrder struct {
	OrderID    int32
	CustomerID int32
	FoodID     int32
	Quantity   int32
}

type Order struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID       int32
	Name     string
	Username string
	Mobile   string
	Password string
	Type     string
}
